# TWRP BoardConfig for IUNI U3
# Actually (03/2016), TWRP < 3.0.0-0 doesn't works on < or = OMNI 6.0 but works on OMNI 5.1

# Platform
TARGET_BOARD_PLATFORM := msm8974
TARGET_BOARD_PLATFORM_GPU := qcom-adreno330

# Flags
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := krait
ARCH_ARM_HAVE_TLS_REGISTER := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := MSM8974
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Krait optimizations
TARGET_USE_KRAIT_BIONIC_OPTIMIZATION := true
TARGET_USE_KRAIT_PLD_SET := true
TARGET_KRAIT_BIONIC_PLDOFFS := 10
TARGET_KRAIT_BIONIC_PLDTHRESH := 10
TARGET_KRAIT_BIONIC_BBTHRESH := 64
TARGET_KRAIT_BIONIC_PLDSIZE := 64

# Kernel
BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=qcom loglevel=1 user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3
BOARD_KERNEL_BASE := 0x0000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --dt device/iuni/u3/dtb --kernel_offset 0x0008000 --ramdisk_offset 0x01000000 --tags_offset 0x0000100
TARGET_KERNEL_ARCH := arm

# prebuilt kernel
TARGET_PREBUILT_KERNEL := device/iuni/u3/kernel
# else uncomment below when IUNI agrees to release the kernel
# TARGET_KERNEL_SOURCE := kernel/iuni/msm8974
# TARGET_KERNEL_CONFIG := cyanogen_u3_defconfig
# apparently this don't work but should
# TARGET_KERNEL_APPEND_DTB := true
# use this instead
# BOARD_KERNEL_IMAGE_NAME := zImage-dtb

# Filesystem
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x1400000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x1400000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824
BOARD_USERDATAIMAGE_PARTITION_SIZE := 29188144128
BOARD_CACHEIMAGE_PARTITION_SIZE := 402653184
BOARD_PERSISTIMAGE_PARTITION_SIZE := 33554432
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PERSISTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# QCOM hardware
BOARD_USES_QCOM_HARDWARE := true
#TARGET_RECOVERY_QCOM_RTC_FIX := true    #ifeq ($(TARGET_CPU_VARIANT),krait)

# Radio
TARGET_RIL_VARIANT := caf

# Assert
TARGET_OTA_ASSERT_DEVICE := u3,U3,IUNI

# Graphics
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024
OVERRIDE_RS_DRIVER := libRSDriver_adreno.so
TARGET_CONTINUOUS_SPLASH_ENABLED := true
TARGET_USES_C2D_COMPOSITION := true
TARGET_USES_ION := true
USE_OPENGL_RENDERER := true
VSYNC_EVENT_PHASE_OFFSET_NS := 2500000
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 0000000

# RPC
TARGET_NO_RPC := true

# TWRP
#TW_CUSTOM_THEME := device/iuni/u3/twres
TW_FLASH_FROM_STORAGE := true
TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
#TW_NO_USB_STORAGE := true
#TW_ALWAYS_RMRF := true
#TW_MAX_BRIGHTNESS := 120
#TW_EXCLUDE_ENCRYPTED_BACKUPS := true
#TW_EXCLUDE_SUPERSU := true
TW_INCLUDE_FB2PNG := true
#TW_USE_TOOLBOX := true
TW_NO_SCREEN_TIMEOUT := true
TW_NO_SCREEN_BLANK := true
TW_INCLUDE_CRYPTO := true
#TW_TARGET_USES_QCOM_BSP := true

# Custom recovery
#TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
RECOVERY_GRAPHICS_USE_LINELENGTH := true
#BOARD_SUPPRESS_SECURE_ERASE := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
#RECOVERY_VARIANT := twrp
BOARD_HAS_NO_SELECT_BUTTON := true
#TARGET_RECOVERY_INITRC := device/iuni/u3/twrp_init.rc
#TARGET_RECOVERY_FSTAB := device/iuni/u3/recovery.fstab
DEVICE_RESOLUTION := 1440x2560
#BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_23x41.h\"
BOARD_TOUCH_RECOVERY := true
BOARD_INCLUDE_FB2PNG := true
#BOARD_CUSTOM_BOOTIMG_MK := device/iuni/u3/custombootimg.mk
